### PR TITLE
[NR-221368] added support for android dynamic feature

### PR DESCRIPTION
**Pull request by ndesai-newrelic**
Our Android agent currently cancels the build process when customers are using Android dynamic features. However, with the latest update, customers can now successfully build their app while utilizing Android dynamic features.

### CODE REVIEW

**Review by ywang-nr — DISMISSED** [review]
Great! Good to know!

**Review by cthomas-newrelic — CHANGES_REQUESTED** [review]
This change alone is insufficient. Needs tests (integration, functional or both , see the repo) and the test harness must be updated to reflect support for the new module type.

**Comment by ndesai-newrelic** [comment]
> This change alone is insufficient. Needs tests (integration, functional or both , see the repo) and the test harness must be updated to reflect support for the new module type.

@cthomas-newrelic i added newrelic plugin on feature module and there is already test for checking dynamic feature. which other tests I can add for this?.

**Review by cthomas-newrelic — COMMENTED** [review]
I think what you're trying to do is write a dynamic feature test app, which is fine, but perhaps in a separate project.

**Pull request closed without merging**
