### PR TITLE
[NR-247776] Report AEI all reasons

### PR DESCRIPTION
**Pull request by ywang-nr**
What's changed:
1. We would like to report all reasons rather than just ANR reason
2. Modify existing unit tests

### CODE REVIEW

**Review by cthomas-newrelic — APPROVED** [review]
👍

**Comment by cthomas-newrelic** [comment]
Oops, just noticed this PR was a draft.

**Comment by ywang-nr** [comment]
> Oops, just noticed this PR was a draft.

Yeah, I was looking into whether we can add more unit tests for other reasons.

**Review by cthomas-newrelic — COMMENTED** [review]
I think this could benefit from additional tests, such as verification that the AEI records we parse end up as correct MobileApplicationExit events with accompanying attributes. Look at the tests I added regarding the importance field in `testApplicationExitImportance`.

**Pull request merged**
